### ISSUE TITLE
Unknown Timezone Error

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/open-web-calendar#190]
Sometimes, the owc has this error:

```
services-open-web-calendar-1  | Traceback (most recent call last):
services-open-web-calendar-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
services-open-web-calendar-1  |     response = self.full_dispatch_request()
services-open-web-calendar-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
services-open-web-calendar-1  |     rv = self.handle_user_exception(e)
services-open-web-calendar-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
services-open-web-calendar-1  |     rv = self.dispatch_request()
services-open-web-calendar-1  |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
services-open-web-calendar-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
services-open-web-calendar-1  |   File "/app/app.py", line 165, in get_calendar
services-open-web-calendar-1  |     strategy = ConvertToDhtmlx(specification, get_text_from_url)
services-open-web-calendar-1  |   File "/app/conversion_base.py", line 25, in __init__
services-open-web-calendar-1  |     self.created()
services-open-web-calendar-1  |   File "/app/convert_to_dhtmlx.py", line 23, in created
services-open-web-calendar-1  |     self.timezone = pytz.timezone(self.specification["timezone"])
services-open-web-calendar-1  |   File "/usr/local/lib/python3.9/site-packages/pytz/__init__.py", line 188, in timezone
services-open-web-calendar-1  |     raise UnknownTimeZoneError(zone)
services-open-web-calendar-1  | pytz.exceptions.UnknownTimeZoneError: ''
```

That is what I have for now: 
```
services-open-web-calendar-1  | pytz.exceptions.UnknownTimeZoneError: ''
services-open-web-calendar-1  | pytz.exceptions.UnknownTimeZoneError: 'Etc/GMT 3'
services-open-web-calendar-1  | pytz.exceptions.UnknownTimeZoneError: 'undefined'
services-open-web-calendar-1  | pytz.exceptions.UnknownTimeZoneError: 'Etc/GMT 5'
services-open-web-calendar-1  | pytz.exceptions.UnknownTimeZoneError: 'undefined'
```

```
docker compose logs open-web-calendar | grep -F .UnknownTimeZoneError | sort | uniq
```

---
<small>
We're using [Polar.sh](https://polar.sh/niccokunzmann) so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/190">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/190/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/190/pledge.svg">
</picture>
</a>

**Comment by niccokunzmann** [comment]
- [ ] This should never fail silently. We want to know these errors.
- [ ] It seems that `'Etc/GMT 3'` is almost understood. This can be changed.
- [ ] If `""` is the timezone, we should use the timezone offset computed by dhtmlx scheduler
- [ ] undefined - interesting should be handled on JS site
- [ ] on error: What do we do - which values do we deliver? Computed offset by dhtmlx scheduler?
