### ISSUE TITLE
error parsing microsoft outlook feeds

### ISSUE THREAD

**Issue by vzaliva** [niccokunzmann/open-web-calendar#482]
I am getting the following error:

```
ValueError
https://outlook.office365.com/owa/calendar/52f6ff2fea444c7f86b80007d565c10a@cam.ac.uk/62a6975b5cb2455bbd85d6576b187db22116294705301331862/calendar.ics

Content line could not be parsed into parts: '<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->': <!-- Copyright (C) Microsoft Corporation. All rights reserved. -->

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 326, in parts
    validate_token(name)
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 115, in validate_token
    raise ValueError(name)
ValueError: <!-- Copyright (C) Microsoft Corporation. All rights reserved. -->

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/open_web_calendar/conversion_base.py", line 85, in retrieve_calendar
    calendars = self.get_calendars_from_url(url)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/open_web_calendar/conversion_base.py", line 62, in get_calendars_from_url
    return Calendar.from_ical(calendar_text, multiple=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 342, in from_ical
    name, params, vals = line.parts()
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 340, in parts
    raise ValueError(
ValueError: Content line could not be parsed into parts: '<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->': <!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
```

I am using the most recent image published on the docker hubL sha256:360b5af3a747026a7aca292df1aec764530639299dd9a5d67ce9e718c438859c

<small>
<hr/>
We're using <a href="https://polar.sh/niccokunzmann">Polar.sh</a> so you can upvote and help fund this issue. We receive the funding once the issue is completed & confirmed by you. Thank you in advance for helping prioritize & fund our work.
</small>

<a href="https://polar.sh/niccokunzmann/open-web-calendar/issues/482">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/482/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/niccokunzmann/open-web-calendar/issues/482/pledge.svg">
</picture>
</a>

**Comment by vzaliva** [comment]
It looks like my URL link was expired. I re-generated it in Outlook and it started working again. Thanks for looking into this!
